version: '3'

services:
    db:
        image: mariadb:latest
        container_name: security-db
        restart: always
        env_file:
            - ./db/.env
        ports:
            - 13306:3306
        volumes:
            - ./db/data:/var/lib/mysql