spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/security
    username: root
    password: voo12voo
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

