server:
  port: 1001

spring:
  datasource:
    url: jdbc:mariadb://localhost:23306/security
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

  #Swagger Error resolve
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379

